import * as microsoftTeams from '@microsoft/teams-js';
import { printLog, formatFileSize } from './../utils/utils';

export const initializeNavigation = () => {
  const logTag = "Navigation"
  output("initializeNavigation")

  // Call the initialize API first
  microsoftTeams.initialize()

  const item1: microsoftTeams.menus.MenuItem = { id: "filter", title: "Filter", viewData: null, enabled: true, selected: false,
    displayMode: microsoftTeams.menus.DisplayMode.ifRoom,
    icon: "PHN2ZyB4bWxuczp4bGluaz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPSczMnB4JyBoZWlnaHQ9JzMycHgnIHZpZXdCb3g9JzAgMCAyOCAyOCcgdmVyc2lvbj0nMS4xJz48ZyBpZD0nUHJvZHVjdC1JY29ucycgc3Ryb2tlPSdub25lJyBzdHJva2Utd2lkdGg9JzEnIGZpbGw9J25vbmUnIGZpbGwtcnVsZT0nZXZlbm9kZCc+PGcgaWQ9J2ljX2ZsdWVudF9maWx0ZXJfMjhfcmVndWxhcicgZmlsbD0nIzIxMjEyMScgZmlsbC1ydWxlPSdub256ZXJvJz48cGF0aCBkPSdNMTcuMjUsMTkgQzE3LjY2NDIxMzYsMTkgMTgsMTkuMzM1Nzg2NCAxOCwxOS43NSBDMTgsMjAuMTY0MjEzNiAxNy42NjQyMTM2LDIwLjUgMTcuMjUsMjAuNSBMMTAuNzUsMjAuNSBDMTAuMzM1Nzg2NCwyMC41IDEwLDIwLjE2NDIxMzYgMTAsMTkuNzUgQzEwLDE5LjMzNTc4NjQgMTAuMzM1Nzg2NCwxOSAxMC43NSwxOSBMMTcuMjUsMTkgWiBNMjEuMjUsMTMgQzIxLjY2NDIxMzYsMTMgMjIsMTMuMzM1Nzg2NCAyMiwxMy43NSBDMjIsMTQuMTY0MjEzNiAyMS42NjQyMTM2LDE0LjUgMjEuMjUsMTQuNSBMNi43NSwxNC41IEM2LjMzNTc4NjQ0LDE0LjUgNiwxNC4xNjQyMTM2IDYsMTMuNzUgQzYsMTMuMzM1Nzg2NCA2LjMzNTc4NjQ0LDEzIDYuNzUsMTMgTDIxLjI1LDEzIFogTTI0LjI1LDcgQzI0LjY2NDIxMzYsNyAyNSw3LjMzNTc4NjQ0IDI1LDcuNzUgQzI1LDguMTY0MjEzNTYgMjQuNjY0MjEzNiw4LjUgMjQuMjUsOC41IEwzLjc1LDguNSBDMy4zMzU3ODY0NCw4LjUgMyw4LjE2NDIxMzU2IDMsNy43NSBDMyw3LjMzNTc4NjQ0IDMuMzM1Nzg2NDQsNyAzLjc1LDcgTDI0LjI1LDcgWicgaWQ9J0NvbG9yJy8+PC9nPjwvZz48L3N2Zz4="
  }

  const item2: microsoftTeams.menus.MenuItem = { id: "newApproval", title: "New Approval Request", viewData: null, enabled: true, selected: false,
    displayMode: microsoftTeams.menus.DisplayMode.ifRoom,
    icon: "PHN2ZyB4bWxuczp4bGluaz0naHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluaycgd2lkdGg9JzMycHgnIGhlaWdodD0nMzJweCcgdmlld0JveD0nMCAwIDI4IDI4Jz48ZyBpZD0nUHJvZHVjdC1JY29ucycgc3Ryb2tlPSdub25lJyBzdHJva2Utd2lkdGg9JzEnIGZpbGw9J25vbmUnIGZpbGwtcnVsZT0nZXZlbm9kZCc+PGcgaWQ9J2ljX2ZsdWVudF9hZGRfMjhfcmVndWxhcicgZmlsbD0nIzIxMjEyMScgZmlsbC1ydWxlPSdub256ZXJvJz48cGF0aCBkPSdNMTQuNSwxMyBMMTQuNSwzLjc1Mzc4NTc3IEMxNC41LDMuMzM5Nzg1NzcgMTQuMTY0LDMuMDAzNzg1NzcgMTMuNzUsMy4wMDM3ODU3NyBDMTMuMzM2LDMuMDAzNzg1NzcgMTMsMy4zMzk3ODU3NyAxMywzLjc1Mzc4NTc3IEwxMywxMyBMMy43NTM4NzU3MywxMyBDMy4zMzk4NzU3MywxMyAzLjAwMzg3NTczLDEzLjMzNiAzLjAwMzg3NTczLDEzLjc1IEMzLjAwMzg3NTczLDE0LjE2NCAzLjMzOTg3NTczLDE0LjUgMy43NTM4NzU3MywxNC41IEwxMywxNC41IEwxMywyMy43NTIzNjUxIEMxMywyNC4xNjYzNjUxIDEzLjMzNiwyNC41MDIzNjUxIDEzLjc1LDI0LjUwMjM2NTEgQzE0LjE2NCwyNC41MDIzNjUxIDE0LjUsMjQuMTY2MzY1MSAxNC41LDIzLjc1MjM2NTEgTDE0LjUsMTQuNSBMMjMuNzQ5ODI2MiwxNC41MDMwNzU0IEMyNC4xNjM4MjYyLDE0LjUwMzA3NTQgMjQuNDk5ODI2MiwxNC4xNjcwNzU0IDI0LjQ5OTgyNjIsMTMuNzUzMDc1NCBDMjQuNDk5ODI2MiwxMy4zMzkwNzU0IDI0LjE2MzgyNjIsMTMuMDAzMDc1NCAyMy43NDk4MjYyLDEzLjAwMzA3NTQgTDE0LjUsMTMgWicgaWQ9J0NvbG9yJy8+PC9nPjwvZz48L3N2Zz4="
  }

  const item3: microsoftTeams.menus.MenuItem = { id: "changeApproval", title: "Change Approval Request", viewData: null, enabled: true, selected: false,
    displayMode: microsoftTeams.menus.DisplayMode.ifRoom,
    icon: "PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgIDxjaXJjbGUgY3g9IjI1IiBjeT0iMjUiIHI9IjIwIi8+Cjwvc3ZnPg=="
  }

  const item4: microsoftTeams.menus.MenuItem = { id: "copyLink", title: "Copy Link", viewData: null, enabled: true, selected: false,
    displayMode: microsoftTeams.menus.DisplayMode.ifRoom,
    icon: "PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTkuMjUgN0M5LjY2NDIxIDcgMTAgNy4zMzU3OSAxMCA3Ljc1QzEwIDguMTI2NTYgOS43MjI0OSA4LjQzODMgOS4zNjA4MyA4LjQ5MTg3TDkuMjUgOC41SDdDNS4wNjcgOC41IDMuNSAxMC4wNjcgMy41IDEyQzMuNSAxMy44NjQgNC45NTcwNyAxNS4zODc2IDYuNzk0MzUgMTUuNDk0MUw3IDE1LjVIOS4yNUM5LjY2NDIxIDE1LjUgMTAgMTUuODM1OCAxMCAxNi4yNUMxMCAxNi42MjY2IDkuNzIyNDkgMTYuOTM4MyA5LjM2MDgzIDE2Ljk5MTlMOS4yNSAxN0g3QzQuMjM4NTggMTcgMiAxNC43NjE0IDIgMTJDMiA5LjMyMjI2IDQuMTA0OTYgNy4xMzYxNSA2Ljc1MDQ1IDcuMDA2MTJMNyA3SDkuMjVaTTE3IDdDMTkuNzYxNCA3IDIyIDkuMjM4NTggMjIgMTJDMjIgMTQuNjc3NyAxOS44OTUgMTYuODYzOCAxNy4yNDk1IDE2Ljk5MzlMMTcgMTdIMTQuNzVDMTQuMzM1OCAxNyAxNCAxNi42NjQyIDE0IDE2LjI1QzE0IDE1Ljg3MzQgMTQuMjc3NSAxNS41NjE3IDE0LjYzOTIgMTUuNTA4MUwxNC43NSAxNS41SDE3QzE4LjkzMyAxNS41IDIwLjUgMTMuOTMzIDIwLjUgMTJDMjAuNSAxMC4xMzYgMTkuMDQyOSA4LjYxMjQgMTcuMjA1NyA4LjUwNTk0TDE3IDguNUgxNC43NUMxNC4zMzU4IDguNSAxNCA4LjE2NDIxIDE0IDcuNzVDMTQgNy4zNzM0NCAxNC4yNzc1IDcuMDYxNyAxNC42MzkyIDcuMDA4MTNMMTQuNzUgN0gxN1pNNyAxMS4yNUgxN0MxNy40MTQyIDExLjI1IDE3Ljc1IDExLjU4NTggMTcuNzUgMTJDMTcuNzUgMTIuMzc5NyAxNy40Njc4IDEyLjY5MzUgMTcuMTAxOCAxMi43NDMyTDE3IDEyLjc1SDdDNi41ODU3OSAxMi43NSA2LjI1IDEyLjQxNDIgNi4yNSAxMkM2LjI1IDExLjYyMDMgNi41MzIxNSAxMS4zMDY1IDYuODk4MjMgMTEuMjU2OEw3IDExLjI1SDE3SDdaIiBmaWxsPSIjMjEyMTIxIi8+Cjwvc3ZnPgo="
  }

  const item5: microsoftTeams.menus.MenuItem = { id: "editInApp", title: "Edit In App", viewData: null, enabled: true, selected: false,
    displayMode: microsoftTeams.menus.DisplayMode.ifRoom,
    icon: "PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik03LjAwMDEyIDE4SDMuMDAwMTJDMi40NTAxMiAxOCAyLjAwMDEyIDE3LjU1IDIuMDAwMTIgMTdWN0MyLjAwMDEyIDYuNDUgMi40NTAxMiA2IDMuMDAwMTIgNkg3LjAwMDEyVjMuODNDNy4wMDAxMiAzLjM3NCA3LjM3MzEyIDMgNy44MzAxMiAzSDIxLjE3MDFDMjEuNjI4MSAzIDIyLjAwMDEgMy4zNzIgMjIuMDAwMSAzLjgzVjIwLjE3QzIyLjAwMDEgMjAuNjI2IDIxLjYyNjEgMjEgMjEuMTcwMSAyMUg3LjgzMDEyQzcuMzcyMTIgMjEgNy4wMDAxMiAyMC42MjggNy4wMDAxMiAyMC4xN1YxOFpNMjEuMDAwMSAxMkgxOC4wMDAxVjlIMjEuMDAwMVYxMlpNMTguMDAwMSAxNkgyMS4wMDAxVjEzSDE4LjAwMDFWMTZaTTIxLjAwMDEgMjBIMTguMDAwMVYxN0gyMS4wMDAxVjIwWk04LjAwMDEyIDRIMjEuMDAwMVY4SDE3LjAwMDFWMjBIOC4wMDAxMlYxOEgxMy4wMDAxQzEzLjU1MDEgMTggMTQuMDAwMSAxNy41NSAxNC4wMDAxIDE3VjdDMTQuMDAwMSA2LjQ1IDEzLjU1MDEgNiAxMy4wMDAxIDZIOC4wMDAxMlY0Wk02LjY3MTEyIDExLjI3Nkw5LjMxMDEyIDE1Ljg3NUgxMS4xNTExVjguMTI1SDkuMzMzMTJWMTIuNTkzTDYuNzg5MTIgOC4xMjVINC44NDkxMlYxNS44NzVINi42NzExMlYxMS4yNzZaIiBmaWxsPSIjMjEyMTIxIi8+Cjwvc3ZnPgo="
  }

  const item6: microsoftTeams.menus.MenuItem = { id: "copyLink", title: "Copy Link 2", viewData: null, enabled: true, selected: false,
    displayMode: microsoftTeams.menus.DisplayMode.ifRoom,
    icon: "PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTkuMjUgN0M5LjY2NDIxIDcgMTAgNy4zMzU3OSAxMCA3Ljc1QzEwIDguMTI2NTYgOS43MjI0OSA4LjQzODMgOS4zNjA4MyA4LjQ5MTg3TDkuMjUgOC41SDdDNS4wNjcgOC41IDMuNSAxMC4wNjcgMy41IDEyQzMuNSAxMy44NjQgNC45NTcwNyAxNS4zODc2IDYuNzk0MzUgMTUuNDk0MUw3IDE1LjVIOS4yNUM5LjY2NDIxIDE1LjUgMTAgMTUuODM1OCAxMCAxNi4yNUMxMCAxNi42MjY2IDkuNzIyNDkgMTYuOTM4MyA5LjM2MDgzIDE2Ljk5MTlMOS4yNSAxN0g3QzQuMjM4NTggMTcgMiAxNC43NjE0IDIgMTJDMiA5LjMyMjI2IDQuMTA0OTYgNy4xMzYxNSA2Ljc1MDQ1IDcuMDA2MTJMNyA3SDkuMjVaTTE3IDdDMTkuNzYxNCA3IDIyIDkuMjM4NTggMjIgMTJDMjIgMTQuNjc3NyAxOS44OTUgMTYuODYzOCAxNy4yNDk1IDE2Ljk5MzlMMTcgMTdIMTQuNzVDMTQuMzM1OCAxNyAxNCAxNi42NjQyIDE0IDE2LjI1QzE0IDE1Ljg3MzQgMTQuMjc3NSAxNS41NjE3IDE0LjYzOTIgMTUuNTA4MUwxNC43NSAxNS41SDE3QzE4LjkzMyAxNS41IDIwLjUgMTMuOTMzIDIwLjUgMTJDMjAuNSAxMC4xMzYgMTkuMDQyOSA4LjYxMjQgMTcuMjA1NyA4LjUwNTk0TDE3IDguNUgxNC43NUMxNC4zMzU4IDguNSAxNCA4LjE2NDIxIDE0IDcuNzVDMTQgNy4zNzM0NCAxNC4yNzc1IDcuMDYxNyAxNC42MzkyIDcuMDA4MTNMMTQuNzUgN0gxN1pNNyAxMS4yNUgxN0MxNy40MTQyIDExLjI1IDE3Ljc1IDExLjU4NTggMTcuNzUgMTJDMTcuNzUgMTIuMzc5NyAxNy40Njc4IDEyLjY5MzUgMTcuMTAxOCAxMi43NDMyTDE3IDEyLjc1SDdDNi41ODU3OSAxMi43NSA2LjI1IDEyLjQxNDIgNi4yNSAxMkM2LjI1IDExLjYyMDMgNi41MzIxNSAxMS4zMDY1IDYuODk4MjMgMTEuMjU2OEw3IDExLjI1SDE3SDdaIiBmaWxsPSIjMjEyMTIxIi8+Cjwvc3ZnPgo="
  }

  const registerBackButton = document.getElementById('registerBackButton') as HTMLButtonElement
  const registerBackReturn = document.querySelector('#registerBackReturn') as HTMLSelectElement
  const setNavBarMenuButton = document.getElementById('setNavBarMenuButton') as HTMLButtonElement
  const setNavBarMenuInput = document.getElementById('setNavBarMenuInput') as HTMLTextAreaElement
  const clearLogs = document.querySelector('#clearLogs') as HTMLButtonElement
  const blobDiv = document.querySelector('#blobs') as HTMLDivElement
  //const menuItems = [item1, item2]
  const menuItems = [item1, item2, item3, item4, item5, item6]

  setNavBarMenuInput.value = JSON.stringify(menuItems, undefined, 4)
  setNavBarMenuInput.style.width = setNavBarMenuInput.parentElement.scrollWidth + "px";
  setNavBarMenuInput.style.height = setNavBarMenuInput.scrollHeight + "px";

  setNavBarMenuButton.onclick = () => {
    const menuItems = JSON.parse(setNavBarMenuInput.value)
    microsoftTeams.menus.setNavBarMenu(menuItems, (id: string) => {
      output(`Clicked ${id}`)
      return true;
    })
  }

  registerBackButton.onclick = () => {
    microsoftTeams.registerBackButtonHandler(() => {
      const selectOption = registerBackReturn.options[registerBackReturn.selectedIndex].value
      var isHandled = false
      if (selectOption == 'true') 
        isHandled = true;
      output(`onBack isHandled ${isHandled}`)
      return isHandled;
    })
  }

  clearLogs.onclick = () => {
    clearLogClick()
  }

  function clearLogClick() {
    (document.querySelector('#logs') as HTMLDivElement).innerText = "";
    blobDiv.innerText = "";
  }

  function output(msg?: string) {
    printLog(logTag, msg)
  }
}